package com.baryberri.a1_feedbackwhenbuttonclicked;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    // Creating object variables.
    // to import the related packages automatically, use 'alt-click(option-click)'
    Button button1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // links the button1 to the object generated by xml.
        // linking the object to the outlet is done by the object id set in xml file.
        // as the findViewById returns the View class, should be casted into specific Button type.
        // R is the class where xml objects are registered, automatically.
        // Therefore each view on xml has its identical id on R class.
        button1 = (Button)findViewById(R.id.button1);

        // Creates the actions that is done when the button is clicked.
        // This is done by a mechanism 'listener'
        // Make a onClickListener that does some certain jobs,
        // and set that listener as the listener of button1.
        // for example, strings can be used like R.string.button1String.
        button1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Print some text on the screen.
                // makeText: context, text, showing duration
                // and the text is shown onto the screen by show method.
                Toast.makeText(getApplicationContext(), "Clicked the button!", Toast.LENGTH_SHORT).show();
            }
        });
    }
}
